### ISSUE TITLE
歌名别名收集

### ISSUE THREAD

**Issue by QingQiz** [QingQiz/QQBOT#1]
这个 ISSUE 用来收集歌曲别名，已有的别名见 [alias.tsv](https://github.com/QingQiz/QQBOT/blob/master/QQBOT.Core/Plugin/PluginResource/MaiMaiDx/aliases.tsv)

**Comment by jiangsuyuan** [comment]
请问，登陆时候的第一个参数，那个地址应该填写什么？

**Comment by QingQiz** [comment]
> 请问，登陆时候的第一个参数，那个地址应该填写什么？

我更新了 readme，你看一下（另外还有问题的话新开一个issue）

**Comment by QingQiz** [comment]
ダンスロボットダンス 作词：ナユタン星人
作曲：ナユタン星人
编曲：ナユタン星人
现有昵称：ダンスロボットダンス，Dance Robot Dance，机器人，drd，dance robot dance，舞动机器人之舞，世界名曲，机器人之舞，机器人舞

**Comment by QingQiz** [comment]
メルティランドナイトメア 作词：はるまきごはん
作曲：はるまきごはん
编曲：はるまきごはん
现有昵称：メルティランドナイトメア，Melty Land Nightmare，melty land nightmare，梦魇，mln，春卷饭，meltyland nightmare，melty，ナイトメア，饭饭
